const http=require("http");
const fs=require("fs");
const path=require("path");
const crypto=require("crypto");
const {execFileSync}=require("child_process");
const {DatabaseSync}=require("node:sqlite");

const ROOT=__dirname, PUBLIC=path.join(ROOT,"public"), UPLOADS=path.join(ROOT,"uploads"), PROJECTS=path.join(UPLOADS,"projects"), IMAGES=path.join(UPLOADS,"images"), DATA=path.join(ROOT,"data");
const PORT=Number(process.env.PORT||3000); const MAX_UPLOAD=50*1024*1024; const MAX_ZIP_FILES=1000; const MAX_EXTRACTED=150*1024*1024;
for(const d of [DATA,UPLOADS,PROJECTS,IMAGES])fs.mkdirSync(d,{recursive:true});
const db=new DatabaseSync(path.join(DATA,"sushant.db"));
db.exec(`PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS projects(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,cat TEXT NOT NULL DEFAULT 'business',description TEXT DEFAULT '',image TEXT DEFAULT '',website_url TEXT DEFAULT '',web_root TEXT DEFAULT '',published INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS enquiries(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT NOT NULL,business TEXT DEFAULT '',message TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'new',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS visits(id INTEGER PRIMARY KEY AUTOINCREMENT,path TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS admin(key TEXT PRIMARY KEY,value TEXT NOT NULL);`);
const DEFAULT={name:"SUSHANT YADAV",phone:"+9779820221555",wa:"9779820221555",email:"",bio:"Premium websites, modern interfaces and digital experiences built with clean code, strong visual design and a focus on helping businesses grow online.",accent:"#d5b16a",mode:"dark",headline:"I'm SUSHANT YADAV. I build the future.",title:"SUSHANT YADAV — Digital Web Developer",desc:"SUSHANT YADAV — premium websites and digital experiences for modern businesses.",showBanner:true,showAnimations:true,scrollTop:true};
const SERVICES=[["Business Websites","Premium websites for restaurants, salons, shops, agencies, startups and local businesses.","⌘"],["Landing Pages","High-impact pages designed around one clear goal: enquiries, calls, bookings or sales.","↗"],["UI / UX Design","Clean layouts, strong hierarchy and intuitive experiences that feel premium on every screen.","◇"],["Speed & Mobile","Responsive websites that remain polished across phones, tablets, laptops and desktops.","⚡"],["SEO Foundation","Semantic structure, metadata and search-friendly foundations for better discoverability.","⌕"],["Support & Updates","Keep your website fresh with content updates, improvements and ongoing support.","∞"]];
function getSettings(){const s={...DEFAULT};for(const r of db.prepare("SELECT key,value FROM settings").all()){try{s[r.key]=JSON.parse(r.value)}catch{s[r.key]=r.value}}return s}
function setSettings(o){const st=db.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value");for(const [k,v] of Object.entries(o||{}))if(k in DEFAULT)st.run(k,JSON.stringify(v))}
if(db.prepare("SELECT COUNT(*) c FROM settings").get().c===0)setSettings(DEFAULT);
if(!db.prepare("SELECT 1 FROM settings WHERE key='services'").get())db.prepare("INSERT INTO settings VALUES('services',?)").run(JSON.stringify(SERVICES));
function services(){try{return JSON.parse(db.prepare("SELECT value FROM settings WHERE key='services'").get().value)}catch{return SERVICES}}
function slugify(s){return String(s||"project").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,60)||"project"}
function uniqueSlug(t,id=0){const b=slugify(t);let s=b,n=2;while(db.prepare("SELECT id FROM projects WHERE slug=? AND id<>?").get(s,id))s=b+"-"+n++;return s}
function projects(all=false){return db.prepare(all?"SELECT * FROM projects ORDER BY id DESC":"SELECT * FROM projects WHERE published=1 ORDER BY id DESC").all().map(p=>({...p,desc:p.description||"",published:!!p.published}))}
function publicData(){const s=getSettings();const ps={starter:{package_key:"starter",package_name:"Starter",price_text:"₹4,999",suffix:"starting",description:"1–3 page responsive website"},business:{package_key:"business",package_name:"Business",price_text:"₹9,999",suffix:"starting",description:"Premium custom business website"},advanced:{package_key:"advanced",package_name:"Custom / Advanced",price_text:"Let's Talk",suffix:"",description:"Advanced features and integrations"}};for(const r of db.prepare("SELECT * FROM pricing").all())ps[r.package_key]={...r};return {...s,services:services(),works:projects(),pricing:ps}}
if(!db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='pricing'").get())db.exec("CREATE TABLE pricing(id INTEGER PRIMARY KEY AUTOINCREMENT,package_key TEXT UNIQUE NOT NULL,package_name TEXT NOT NULL,price_text TEXT NOT NULL,suffix TEXT DEFAULT '',description TEXT DEFAULT '')");
if(db.prepare("SELECT COUNT(*) c FROM pricing").get().c===0){const st=db.prepare("INSERT INTO pricing(package_key,package_name,price_text,suffix,description) VALUES(?,?,?,?,?)");st.run("starter","Starter","₹4,999","starting","1–3 page responsive website");st.run("business","Business","₹9,999","starting","Premium custom business website");st.run("advanced","Custom / Advanced","Let's Talk","","Advanced features and integrations")}

// Simple, dependency-free cookie sessions. Password is stored as a scrypt hash.
const USER=process.env.ADMIN_USER||"admin"; const SESSION_SECRET=process.env.ADMIN_SECRET||crypto.randomBytes(32).toString("hex");
function hashPassword(p,salt=crypto.randomBytes(16).toString("hex")){return salt+":"+crypto.scryptSync(p,salt,64).toString("hex")}
function verifyPassword(p,stored){const [salt,h]=String(stored).split(":");if(!salt||!h)return false;const got=crypto.scryptSync(p,salt,64);return crypto.timingSafeEqual(got,Buffer.from(h,"hex"))}
let adminRow=db.prepare("SELECT value FROM admin WHERE key='password'").get();if(!adminRow)db.prepare("INSERT INTO admin(key,value) VALUES('password',?)").run(hashPassword(process.env.ADMIN_PASS||"Sushant@123"));
const sessions=new Map(), attempts=new Map();
function cookie(req){const x=(req.headers.cookie||"").split(";").map(v=>v.trim()).find(v=>v.startsWith("sy_session="));return x?decodeURIComponent(x.slice(11)):""}
function auth(req){const id=cookie(req),x=sessions.get(id);if(!x||x.exp<Date.now()){if(id)sessions.delete(id);return false}return true}
function setSession(res){const id=crypto.randomBytes(32).toString("hex");sessions.set(id,{exp:Date.now()+8*60*60*1000});res.setHeader("Set-Cookie",`sy_session=${id}; Path=/; HttpOnly; SameSite=Lax; Max-Age=28800`)}
function clearSession(res){res.setHeader("Set-Cookie","sy_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0")}
function rate(req){const key=req.socket.remoteAddress||"local", now=Date.now(), a=(attempts.get(key)||[]).filter(t=>now-t<15*60*1000);if(a.length>=10){attempts.set(key,a);return false}a.push(now);attempts.set(key,a);return true}
function json(res,status,obj){const b=JSON.stringify(obj);res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"});res.end(b)}
function send(res,status,text,type="text/plain; charset=utf-8"){res.writeHead(status,{"Content-Type":type,"X-Content-Type-Options":"nosniff"});res.end(text)}
function readBody(req,limit=2*1024*1024){return new Promise((resolve,reject)=>{let n=0,a=[];req.on("data",c=>{n+=c.length;if(n>limit){reject(Error("Request too large"));req.destroy()}else a.push(c)});req.on("end",()=>resolve(Buffer.concat(a)));req.on("error",reject)})}
function parseJson(req){return readBody(req).then(b=>{try{return JSON.parse(b.toString()||"{}")}catch{throw Error("Invalid JSON")}})}
function parseCookiesSafe(req){return cookie(req)}
function requireAdmin(req,res){if(!auth(req)){json(res,401,{error:"Admin login required"});return false}return true}
function multipart(req){return readBody(req,MAX_UPLOAD+5*1024*1024).then(raw=>{const ct=req.headers["content-type"]||"",m=ct.match(/boundary=(?:"([^"]+)"|([^;]+))/);if(!m)throw Error("Multipart upload required");const boundary=Buffer.from("--"+(m[1]||m[2]));const out={fields:{},files:{}};let pos=0;while((pos=raw.indexOf(boundary,pos))!==-1){let s=pos+boundary.length;if(raw[s]===13&&raw[s+1]===10)s+=2;const e=raw.indexOf(boundary,s);if(e<0)break;let part=raw.slice(s,e);if(part.slice(-2).toString()==="\r\n")part=part.slice(0,-2);const sep=part.indexOf(Buffer.from("\r\n\r\n"));if(sep<0){pos=e;continue}const h=part.slice(0,sep).toString();const data=part.slice(sep+4);const nm=h.match(/name="([^"]+)"/i),fm=h.match(/filename="([^"]*)"/i);if(!nm){pos=e;continue}if(fm){out.files[nm[1]]={name:path.basename(fm[1]),type:(h.match(/Content-Type:\s*([^\r\n]+)/i)||[])[1]||"application/octet-stream",buffer:data}}else out.fields[nm[1]]=data.toString();pos=e}return out})}
function saveImage(file){if(!file)return"";if(!/^image\/(png|jpe?g|webp|gif)$/i.test(file.type))throw Error("Project image must be PNG, JPG, WEBP or GIF");const ext=path.extname(file.name).toLowerCase()||".jpg",n=crypto.randomUUID()+ext;fs.writeFileSync(path.join(IMAGES,n),file.buffer);return "/uploads/images/"+n}
function safeZipList(file){const tmp=path.join(UPLOADS,"."+crypto.randomUUID()+".zip");fs.writeFileSync(tmp,file.buffer);let list;try{list=execFileSync("unzip",["-Z1",tmp],{encoding:"utf8",maxBuffer:5*1024*1024}).split(/\r?\n/).filter(Boolean)}catch(e){fs.rmSync(tmp,{force:true});throw Error("Invalid ZIP file or unzip is unavailable on this server")};if(list.length>MAX_ZIP_FILES){fs.rmSync(tmp,{force:true});throw Error("ZIP contains too many files (maximum 1000)")};for(const n of list){const x=n.replace(/\\/g,"/");if(x.startsWith("/")||x.split("/").includes("..")||/^[A-Za-z]:/.test(x)||x.includes("\0")){fs.rmSync(tmp,{force:true});throw Error("Unsafe path in ZIP file")}}
let total=0;try{const info=execFileSync("unzip",["-l",tmp],{encoding:"utf8"});for(const line of info.split(/\r?\n/)){const m=line.match(/^\s*(\d+)\s+\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}\s+(.+)$/);if(m)total+=Number(m[1]);}}catch{}if(total>MAX_EXTRACTED){fs.rmSync(tmp,{force:true});throw Error("ZIP expands beyond the 150 MB limit")}
return {tmp,list};}
function extractZip(file,target){const {tmp,list}=safeZipList(file);try{execFileSync("unzip",["-q",tmp,"-d",target],{stdio:"ignore"});for(const n of list){const p=path.join(target,n);if(fs.existsSync(p)&&fs.lstatSync(p).isSymbolicLink())throw Error("Symbolic links are not allowed in website ZIPs")}const html=list.find(n=>!n.endsWith("/")&&/(^|\/)index\.html?$/i.test(n));if(!html)throw Error("ZIP must contain an index.html file");return path.dirname(html.replace(/\\/g,"/"));}finally{fs.rmSync(tmp,{force:true})}}
function removeDir(slug){fs.rmSync(path.join(PROJECTS,slug),{recursive:true,force:true})}
function publicFile(req,res){let p=decodeURIComponent(req.url.split("?")[0]);if(p==="/admin")p="/index.html";if(p==="/")p="/index.html";const base=p.startsWith("/uploads/")?UPLOADS:PUBLIC;const rel=p.startsWith("/uploads/")?p.slice("/uploads/".length):p.replace(/^\//,"");const fp=path.resolve(base,rel);const root=path.resolve(base);if(!fp.startsWith(root+path.sep))return send(res,403,"Forbidden");if(fs.existsSync(fp)&&fs.statSync(fp).isFile()){const ext=path.extname(fp).toLowerCase(),types={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".gif":"image/gif",".svg":"image/svg+xml",".ico":"image/x-icon",".json":"application/json; charset=utf-8",".woff":"font/woff",".woff2":"font/woff2"};res.writeHead(200,{"Content-Type":types[ext]||"application/octet-stream","X-Content-Type-Options":"nosniff","Cache-Control":"no-cache"});return fs.createReadStream(fp).pipe(res)}send(res,404,"Not found")}
function serveProject(req,res,slug,rest){const p=db.prepare("SELECT * FROM projects WHERE slug=?").get(slug);if(!p||!p.website_url||(!p.published&&!auth(req)))return send(res,404,"Project not found");const root=path.resolve(PROJECTS,p.slug,p.web_root||"");if(!root.startsWith(path.resolve(PROJECTS)+path.sep)||!fs.existsSync(root))return send(res,404,"Website files not found");let rel=rest||"/";const fp=path.resolve(root,"."+rel);if(!fp.startsWith(root+path.sep)&&fp!==root)return send(res,403,"Forbidden");if(fs.existsSync(fp)&&fs.statSync(fp).isFile()){const ext=path.extname(fp).toLowerCase(),types={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".gif":"image/gif",".svg":"image/svg+xml",".ico":"image/x-icon",".json":"application/json"};res.writeHead(200,{"Content-Type":types[ext]||"application/octet-stream","X-Content-Type-Options":"nosniff"});return fs.createReadStream(fp).pipe(res)}const idx=path.join(root,"index.html");if(fs.existsSync(idx))return fs.createReadStream(idx).pipe(Object.assign(res,{statusCode:200}));send(res,404,"Page not found")}

const server=http.createServer(async(req,res)=>{try{
 const u=new URL(req.url,"http://localhost"),p=u.pathname;
 if(p==="/favicon.ico")return send(res,204,"");
 if(p==="/api/public-data"&&req.method==="GET")return json(res,200,publicData());
 if(p==="/api/visit"&&req.method==="POST"){let x={};try{x=await parseJson(req)}catch{}db.prepare("INSERT INTO visits(path) VALUES(?)").run(String(x.path||"/"));return json(res,200,{ok:true})}
 if(p==="/api/enquiries"&&req.method==="POST"){const x=await parseJson(req);if(!String(x.name||"").trim()||!String(x.phone||"").trim())return json(res,400,{error:"Name and phone are required"});db.prepare("INSERT INTO enquiries(name,phone,business,message) VALUES(?,?,?,?)").run(String(x.name).trim(),String(x.phone).trim(),String(x.business||"").trim(),String(x.message||"").trim());return json(res,201,{ok:true})}
 if(p==="/api/login"&&req.method==="POST"){if(!rate(req))return json(res,429,{error:"Too many login attempts. Try again in 15 minutes."});const x=await parseJson(req);const row=db.prepare("SELECT value FROM admin WHERE key='password'").get();if(x.username===USER&&verifyPassword(String(x.password||""),row.value)){attempts.delete(req.socket.remoteAddress||"local");setSession(res);return json(res,200,{ok:true})}return json(res,401,{error:"Incorrect username or password."})}
 if(p==="/api/logout"&&req.method==="POST"){sessions.delete(parseCookiesSafe(req));clearSession(res);return json(res,200,{ok:true})}
 if(p==="/api/admin/data"&&req.method==="GET"){if(!requireAdmin(req,res))return;const s=getSettings();return json(res,200,{...s,services:services(),works:projects(true),pricing:db.prepare("SELECT * FROM pricing ORDER BY id").all(),enquiries:db.prepare("SELECT * FROM enquiries ORDER BY id DESC LIMIT 100").all(),stats:{projects:db.prepare("SELECT COUNT(*) c FROM projects").get().c,published:db.prepare("SELECT COUNT(*) c FROM projects WHERE published=1").get().c,enquiries:db.prepare("SELECT COUNT(*) c FROM enquiries").get().c,newEnquiries:db.prepare("SELECT COUNT(*) c FROM enquiries WHERE status='new'").get().c,visits:db.prepare("SELECT COUNT(*) c FROM visits").get().c}})}
 if(p==="/api/admin/settings"&&req.method==="PUT"){if(!requireAdmin(req,res))return;setSettings(await parseJson(req));return json(res,200,{ok:true,data:publicData()})}
 if(p==="/api/admin/services"&&req.method==="PUT"){if(!requireAdmin(req,res))return;const x=await parseJson(req);if(!Array.isArray(x.services))return json(res,400,{error:"Invalid services"});db.prepare("INSERT INTO settings(key,value) VALUES('services',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify(x.services));return json(res,200,{ok:true,data:publicData()})}
 if(p==="/api/admin/pricing"&&req.method==="PUT"){if(!requireAdmin(req,res))return;const x=await parseJson(req);const st=db.prepare("UPDATE pricing SET package_name=?,price_text=?,suffix=?,description=? WHERE id=?");st.run(String(x.package_name),String(x.price_text),String(x.suffix||""),String(x.description||""),Number(x.id));return json(res,200,{ok:true,data:publicData()})}
 if(p==="/api/admin/password"&&req.method==="PUT"){if(!requireAdmin(req,res))return;const x=await parseJson(req);const row=db.prepare("SELECT value FROM admin WHERE key='password'").get();if(!verifyPassword(String(x.current||""),row.value))return json(res,400,{error:"Current password is incorrect"});if(String(x.next||"").length<10)return json(res,400,{error:"New password must be at least 10 characters"});db.prepare("UPDATE admin SET value=? WHERE key='password'").run(hashPassword(String(x.next)));sessions.clear();setSession(res);return json(res,200,{ok:true})}
 if(p==="/api/admin/enquiries"&&req.method==="PUT"){if(!requireAdmin(req,res))return;const x=await parseJson(req);db.prepare("UPDATE enquiries SET status=? WHERE id=?").run(["new","contacted","closed"].includes(x.status)?x.status:"new",Number(x.id));return json(res,200,{ok:true})}
 if(p==="/api/admin/enquiries"&&req.method==="DELETE"){if(!requireAdmin(req,res))return;const x=await parseJson(req);db.prepare("DELETE FROM enquiries WHERE id=?").run(Number(x.id));return json(res,200,{ok:true})}
 if(p==="/api/admin/backup"&&req.method==="GET"){if(!requireAdmin(req,res))return;const payload={version:1,exported_at:new Date().toISOString(),settings:getSettings(),services:services(),pricing:db.prepare("SELECT package_key,package_name,price_text,suffix,description FROM pricing ORDER BY id").all(),projects:projects(true),enquiries:db.prepare("SELECT name,phone,business,message,status,created_at FROM enquiries ORDER BY id").all()};return json(res,200,payload)}
 if(p==="/api/admin/restore"&&req.method==="POST"){if(!requireAdmin(req,res))return;const x=await parseJson(req,10*1024*1024);if(!x||!x.settings)return json(res,400,{error:"Invalid backup"});setSettings(x.settings);if(Array.isArray(x.services))db.prepare("INSERT INTO settings(key,value) VALUES('services',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify(x.services));if(Array.isArray(x.pricing)){const st=db.prepare("UPDATE pricing SET package_name=?,price_text=?,suffix=?,description=? WHERE package_key=?");for(const q of x.pricing)st.run(q.package_name,q.price_text,q.suffix||"",q.description||"",q.package_key)}return json(res,200,{ok:true,data:publicData()})}
 if(p==="/api/admin/reset"&&req.method==="POST"){if(!requireAdmin(req,res))return;for(const q of db.prepare("SELECT slug FROM projects").all())removeDir(q.slug);db.exec("DELETE FROM projects; DELETE FROM enquiries; DELETE FROM visits; DELETE FROM settings;");setSettings(DEFAULT);db.prepare("INSERT INTO settings VALUES('services',?)").run(JSON.stringify(SERVICES));return json(res,200,{ok:true,data:publicData()})}
 if(p==="/api/projects"&&req.method==="POST"){if(!requireAdmin(req,res))return;const m=await multipart(req);const title=String(m.fields.title||"").trim();if(!title)return json(res,400,{error:"Project title is required"});const slug=uniqueSlug(title),dir=path.join(PROJECTS,slug);fs.mkdirSync(dir,{recursive:true});let url="",root="";const web=m.files.website;if(web){if(/\.zip$/i.test(web.name))root=extractZip(web,dir);else{if(!/\.html?$/i.test(web.name))throw Error("Website must be HTML or ZIP");fs.writeFileSync(path.join(dir,"index.html"),web.buffer)}url="/project/"+slug+"/"}const image=saveImage(m.files.image);db.prepare("INSERT INTO projects(title,slug,cat,description,image,website_url,web_root,published) VALUES(?,?,?,?,?,?,?,?)").run(title,slug,m.fields.cat||"business",m.fields.desc||"",image,url,root,m.fields.published==="0"?0:1);return json(res,201,{ok:true,data:publicData()})}
 if(p.startsWith("/api/projects/")&&req.method==="DELETE"){if(!requireAdmin(req,res))return;const id=Number(p.split("/").pop()),q=db.prepare("SELECT * FROM projects WHERE id=?").get(id);if(!q)return json(res,404,{error:"Project not found"});db.prepare("DELETE FROM projects WHERE id=?").run(id);removeDir(q.slug);return json(res,200,{ok:true,data:publicData()})}
 if(p.startsWith("/api/projects/")&&req.method==="PUT"){if(!requireAdmin(req,res))return;const id=Number(p.split("/").pop()),old=db.prepare("SELECT * FROM projects WHERE id=?").get(id);if(!old)return json(res,404,{error:"Project not found"});const m=await multipart(req),title=String(m.fields.title||old.title).trim(),slug=uniqueSlug(title,id);let image=old.image;if(m.files.image)image=saveImage(m.files.image);if(slug!==old.slug){const a=path.join(PROJECTS,old.slug),b=path.join(PROJECTS,slug);if(fs.existsSync(a))fs.renameSync(a,b)}let weburl=old.website_url?"/project/"+slug+"/":"",root=old.web_root||"";if(m.files.website){removeDir(slug);fs.mkdirSync(path.join(PROJECTS,slug),{recursive:true});const w=m.files.website;if(/\.zip$/i.test(w.name))root=extractZip(w,path.join(PROJECTS,slug));else{root="";fs.writeFileSync(path.join(PROJECTS,slug,"index.html"),w.buffer)}weburl="/project/"+slug+"/"}db.prepare("UPDATE projects SET title=?,slug=?,cat=?,description=?,image=?,website_url=?,web_root=?,published=? WHERE id=?").run(title,slug,m.fields.cat||old.cat,m.fields.desc??old.description,image,weburl,root,m.fields.published==="0"?0:1,id);return json(res,200,{ok:true,data:publicData()})}
 if(p.startsWith("/project/")){const bits=p.split("/");return serveProject(req,res,bits[2],"/"+bits.slice(3).join("/"))}
 if(req.method==="GET")return publicFile(req,res);
 send(res,404,"Not found");
}catch(e){console.error(e);if(!res.headersSent)json(res,500,{error:e.message||"Server error"})}});
server.listen(PORT,()=>console.log(`SUSHANT YADAV website: http://localhost:${PORT}`));
process.on("SIGINT",()=>{try{db.close()}catch{}process.exit(0)});
